"""empty message

Revision ID: 75938a37a1b3
Revises: 90bc89b06409
Create Date: 2023-07-16 12:07:34.817416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75938a37a1b3'
down_revision = '90bc89b06409'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tour', ['tourId'], ['id'])

    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'sport', ['sportId'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
